/*
	Name: Michal Drahorat
	Date: October 6th, 2017
*/

CREATE TABLE Developer (
	id INTEGER PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Category (
	id INTEGER PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Platform (
	id INTEGER PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL UNIQUE
);
CREATE TABLE Employee(
	id INTEGER PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
	username VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	name VARCHAR(20) NOT NULL,
	surname VARCHAR(20) NOT NULL,
	phone VARCHAR(10) NOT NULL,
	email VARCHAR(255) NOT NULL
);

CREATE TABLE Game(
	id INTEGER PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
	game_name VARCHAR(255) UNIQUE NOT NULL,
	price NUMERIC(5,2) NOT NULL,
	EmployeeId INTEGER NOT NULL,
	DeveloperId INTEGER NOT NULL,
	CategoryId INTEGER NOT NULL,
	FOREIGN KEY (EmployeeId) REFERENCES employee(id),
	FOREIGN KEY (DeveloperId) REFERENCES developer(id),
	FOREIGN KEY (CategoryId) REFERENCES category(id)
);



CREATE TABLE Event(
	event_id INTEGER PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
	event_name VARCHAR(255) NOT NULL,
	event_date date NOT NULL,
    event_time time,
	location VARCHAR(255) NOT NULL,
	event_price DECIMAL(4,2),
	EmployeeId INTEGER NOT NULL,
	FOREIGN KEY (EmployeeId) REFERENCES employee(id)
);

CREATE TABLE Reviews(
	review_id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
	review_approved TINYINT(1),
	review_rating INTEGER(1) NOT NULL,
	reviewText VARCHAR(255),
	GameId INTEGER NOT NULL,
	MemberId INTEGER NOT NULL,
	FOREIGN KEY (GameId) REFERENCES game(id),
	FOREIGN KEY (MemberId) REFERENCES member(id)
);



