//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSnipeWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int id { get; set; }
        public byte Approved { get; set; }
        public int Gameid { get; set; }
        public int MemberID { get; set; }
        public int Rating { get; set; }
        public string ReviewText { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Member Member { get; set; }
    }
}
